[package]
name = "day-4"
version = "0.1.0"
authors = ["Raoul Hidalgo Charman <raoul.hidalgo.charman@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1.2.0"
chrono = "0.4"

[profile.dev]
opt-level = 3
